### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Shadowblitz16** [alternetsoft/AlternetUI#86]
I get this when trying to run Install.sh
```
  Downloading 36%   
  Downloading 37%   
  Downloading 38%   
  Downloading 39%   
  Downloading 40%   
  Unhandled exception. System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
   ---> System.Net.Sockets.SocketException (104): Connection reset by peer
     --- End of inner exception stack trace ---
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
     at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
     at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
     at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
     at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
     at Alternet.UI.HttpClientProgressExtensions.CopyToAsync(Stream source, Stream destination, Int32 bufferSize, IProgress`1 progress, CancellationToken cancellationToken) in /home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Tools/Alternet.UI.CommonUtils/HttpClientProgressExtensions.cs:line 45
     at Alternet.UI.HttpClientProgressExtensions.DownloadDataAsync(HttpClient client, String requestUrl, Stream destination, IProgress`1 progress, CancellationToken cancellationToken) in /home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Tools/Alternet.UI.CommonUtils/HttpClientProgressExtensions.cs:line 24
     at Alternet.UI.CommonProcs.DownloadFile(String docUrl, String filePath, EventHandler`1 progressChanged) in /home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Tools/Alternet.UI.CommonUtils/CommonUtilsDownloadFile.cs:line 70
     at Alternet.UI.CommonProcs.DownloadFileWithConsoleProgress(String docUrl, String filePath) in /home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Tools/Alternet.UI.CommonUtils/CommonUtilsDownloadFile.cs:line 38
     at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Tools/Alternet.UI.RunCmd/Program.cs:line 43
     at Program.<Main>(String[] args)
  Downloading 41%   
/home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Build/Alternet.UI.Pal/Alternet.UI.Pal.WxWidgets.targets(61,9): error MSB3073: The command "dotnet run -- -r=download Url="https://alternetsoftware.blob.core.windows.net/alternet-ui/wxWidgets-bin-noobjpch-3.2.3.zip" Path="/home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Build/Alternet.UI.Pal/../../../External//WxWidgets.zip"" exited with code 134. [/home/shadowblitz16/Documents/Source/cs/AlternetUI/Source/Build/Alternet.UI.Pal/Alternet.UI.Pal.proj]
```

**Comment by generalloki** [comment]
It downloads fine right now. I have no idea what was wrong. Try do download it now.
We will think on some solution, it could be using 7zip instead of zip for large files or changing host. I will post here an update in this case.

**Comment by generalloki** [comment]
If it worked, I am closing the issue.
